version: "3.9"
services: 
    inventory:
        build: .
        ports: 
            - 8080:8080
        environment: 
            MYSQL_SERVER: mysql
    mysql:
        image: mysql:8.0
        volumes: 
            - mysql_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 'qtdevops'
            MYSQL_DATABASE: qtinvsrv
            MYSQL_USER: 'qtdevops'
            MYSQL_PASSWORD: 'qtdevops'
volumes: 
    mysql_data: {}